pull_request_rules:
  - name: Auto-approve PR from author when checks pass
    conditions:
      - author=nickwilsonr
      - base=master
      - status-success=Run flake8
    actions:
      approve:
