pull_request_rules:
  - name: Auto-approve PR from author when checks pass
    conditions:
      - author = nickwilsonr
      - base = master
      - check-success = Run flake8
    actions:
      review:
        type: APPROVE

merge_protections: []
